### ISSUE TITLE
Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by hcxiong** [iVanPan/Cordova_QQ#10]
无法删除cordova-plugin-qqsdk，其它第三方插件都可以删除。
sudo cordova plugin remove cordova-plugin-qqsdk
Running android-install.Hook: before_plugin_rm, Package: cn.org.smhc.moodthermo, Path: /Users/hcxiong/happi_pro/git_pro/NerveApp3.
Uninstalling cordova-plugin-qqsdk from android
Uninstalling cordova-plugin-qqsdk from ios
TypeError: Cannot read property 'buffer' of undefined
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:131:18)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:98:7)
    at walk_obj (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:109:9)
    at Object.build (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/plist/lib/build.js:76:3)
    at ConfigFile_save [as save](/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigFile.js:97:47)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:61:49
    at Array.forEach (native)
    at ConfigKeeper_save_all [as save_all](/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/ConfigKeeper.js:59:31)
    at PlatformMunger_save_all [as save_all](/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:82:24)
    at Object.exports.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:59:12)
cordova -v 5.1.1/5.3.1 都试过无法删除

id="cordova-plugin-qqsdk"  version="0.3.6"

**Comment by iVanPan** [comment]
@hcxiong  感谢反馈，这个是cordova的一个bug，你可以在这里查看https://issues.apache.org/jira/browse/CB-7781，https://github.com/aetchegoyen/plist.js/commit/6eed7aedbee90db2315b985cb952778696190ba0 这个是修复补丁 只要修改cordova的node_modules 里面的plist 模块的build.js 即可。已亲测有效！

**Comment by hcxiong** [comment]
非常感谢，现在可以了。
