### ISSUE TITLE
Android QQ Logon Flash

### ISSUE THREAD

**Issue by LaySolitary** [iVanPan/Cordova_QQ#96]
ActivityManager: Unable to start service Intent { cmp=com.tencent.mobileqq/.qipc.QIPCService } U=0: not found
 waitInit when empty: 
 java.lang.RuntimeException: 
        at mqq.app.MobileQQ.waitAppRuntime(MobileQQ.java:771)
        at com.tencent.common.app.BaseApplicationImpl.getRuntime(ProGuard:198)
        at com.tencent.mobileqq.app.DeviceProfileManager.a(ProGuard:284)
        at com.tencent.mobileqq.statistics.battery.BatteryStatsImpl.a(ProGuard:223)
        at com.tencent.mobileqq.statistics.battery.BatteryStatsImpl.a(ProGuard:154)
 	at amib.run(ProGuard:79)
  	at mqq.os.MqqHandler.handleCallback(MqqHandler.java:337)
        at mqq.os.MqqHandler.dispatchMessage(MqqHandler.java:97)
  	at mqq.os.MqqHandler$NativeHandler.dispatchMessage(MqqHandler.java:350)
 	at android.os.Looper.loop(Looper.java:173)
 	at android.os.HandlerThread.run(HandlerThread.java:65)
      doInit begin withcom.tencent.mobileqq:MSF
     doInit finished
 MSF.C.PushManager: info.installVersion :999 strVersionCode:999 sendMsgPushRegister now
 tencent.mm:push: type=1400 audit(0.0:1349935): avc: denied { read } for name="anr" dev="dm-1" ino=2080769 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:anr_data_file:s0 tclass=dir permissive=0

                                  help  me

**Comment by LaySolitary** [comment]
Question mobile information:Honor 9; Android version:8.0.0 EMUI version:8.0.0；Model：LLD-AL 10
